* My Emacs

** Basic Requirement 
   - [-]General[0%] 
     - [ ]theme
       - [X]gui mode
       - [ ]terminal mode
     - [X]modeline 
   - [-]C/C++ support[0%]
     - [X]auto-complete
     - [X]goto header file
     - [X]goto definition
     - [X]goto declaration
     - [X]clang-format support
     - [ ]cmake support
   - [ ]Python support
   - [ ]gdb support
   - [ ]git support - magit
   - [ ]project management
   - [ ]latex support
   - [ ]org mode
     - [ ]indent
     - [ ]preview
     - [X]plantuml
     - [ ]fancy highlight of code blocks

*** General
**** theme 
     GUI mode - using doom-themes
     Terminal mode - not decided, font/color/background should be repicked
**** mode line
     Powerline package is used, see lisp/init-general.el.
**** ace-window
     ace-window is used to switch from window to window.
**** swiper
     use swiper to do the searching

**** helm
**** keyfreq     
     Keyfreq is used to analyze key using statistics in emacs. 

     Include the following lines in your .emacs file:

(require 'keyfreq)
(keyfreq-mode 1)
(keyfreq-autosave-mode 1)
And use keyfreq-show to see how many times you used a command.

How to exclude commands?

(setq keyfreq-excluded-commands
      '(self-insert-command
        forward-char
        backward-char
        previous-line
        next-line))
     

*** C/C++ support
***** Semantic 
     Now Semantic can search system include path and current path, but it still cannot access all includes in local project. So sometimes auto-complete cannot work. 
     Project includes are added into cedet-user-include-dirs to make sure semantics can access all the project includes. 
     
***** helm-gtags
      gtags works well. I can enjoy code navigation.

*** Projectile
    Here projectile is integrated in helm. 

    Keybindings:(with C-c p prefix)
    C-c p f - helm-projectile-find-file-dwin
    


** Key Bindings

| key | function                        |
|-----+---------------------------------|
| F1  | open init.el in .emacs.d folder |
| F2  | open vterm in other window      |
| F3  |                                 |
| F4  |                                 |
| F5  |                                 |
| F6  |                                 |
| F7  |                                 |
| F8  |                                 |
| F9  |                                 |
| F10 |                                 |
| F11 |                                 |
| F12 | load init.el                    |



